# Generated by Django 2.2.3 on 2019-07-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='tweet',
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
